export const wineRegions = [
  // France
  "Bordeaux, France",
  "Burgundy, France",
  "Champagne, France",
  "Rhône Valley, France",
  "Loire Valley, France",
  "Alsace, France",
  "Languedoc-Roussillon, France",
  "Provence, France",
  "Beaujolais, France",
  "Corsica, France",
  "Jura, France",
  "Savoie, France",
  "Southwest France",

  // Italy
  "Tuscany, Italy",
  "Piedmont, Italy",
  "Veneto, Italy",
  "Sicily, Italy",
  "Lombardy, Italy",
  "Emilia-Romagna, Italy",
  "Umbria, Italy",
  "Marche, Italy",
  "Abruzzo, Italy",
  "Puglia, Italy",
  "Campania, Italy",
  "Sardinia, Italy",
  "Friuli-Venezia Giulia, Italy",
  "Trentino-Alto Adige, Italy",
  "Liguria, Italy",
  "Lazio, Italy",
  "Basilicata, Italy",
  "Calabria, Italy",
  "Molise, Italy",
  "Valle d'Aosta, Italy",

  // Spain
  "Rioja, Spain",
  "Ribera del Duero, Spain",
  "Priorat, Spain",
  "Rías Baixas, Spain",
  "Jerez, Spain",
  "Penedès, Spain",
  "Rueda, Spain",
  "Toro, Spain",
  "Jumilla, Spain",
  "Valencia, Spain",
  "La Mancha, Spain",
  "Navarra, Spain",
  "Bierzo, Spain",
  "Mallorca, Spain",
  "Canary Islands, Spain",
  "Galicia, Spain",
  "Catalonia, Spain",

  // Portugal
  "Douro Valley, Portugal",
  "Alentejo, Portugal",
  "Vinho Verde, Portugal",
  "Dão, Portugal",
  "Bairrada, Portugal",
  "Lisboa, Portugal",
  "Tejo, Portugal",
  "Setúbal, Portugal",
  "Madeira, Portugal",
  "Azores, Portugal",

  // Germany
  "Mosel, Germany",
  "Rheingau, Germany",
  "Pfalz, Germany",
  "Rheinhessen, Germany",
  "Baden, Germany",
  "Württemberg, Germany",
  "Franken, Germany",
  "Nahe, Germany",
  "Ahr, Germany",
  "Mittelrhein, Germany",
  "Saale-Unstrut, Germany",
  "Sachsen, Germany",

  // Austria
  "Wachau, Austria",
  "Kamptal, Austria",
  "Kremstal, Austria",
  "Burgenland, Austria",
  "Steiermark (Styria), Austria",
  "Vienna, Austria",

  // United States
  "Napa Valley, California",
  "Sonoma County, California",
  "Paso Robles, California",
  "Santa Barbara County, California",
  "Mendocino County, California",
  "Monterey County, California",
  "San Luis Obispo County, California",
  "Lodi, California",
  "Sierra Foothills, California",
  "Livermore Valley, California",
  "Anderson Valley, California",
  "Russian River Valley, California",
  "Carneros, California",
  "Willamette Valley, Oregon",
  "Columbia Valley, Washington",
  "Walla Walla Valley, Washington",
  "Yakima Valley, Washington",
  "Finger Lakes, New York",
  "Long Island, New York",
  "Hudson Valley, New York",
  "Texas Hill Country, Texas",
  "Virginia",

  // Australia
  "Barossa Valley, Australia",
  "Margaret River, Australia",
  "Hunter Valley, Australia",
  "Clare Valley, Australia",
  "Eden Valley, Australia",
  "McLaren Vale, Australia",
  "Yarra Valley, Australia",
  "Mornington Peninsula, Australia",
  "Tasmania, Australia",
  "Coonawarra, Australia",
  "Adelaide Hills, Australia",
  "Limestone Coast, Australia",
  "Rutherglen, Australia",

  // New Zealand
  "Marlborough, New Zealand",
  "Central Otago, New Zealand",
  "Hawke's Bay, New Zealand",
  "Martinborough, New Zealand",
  "Gisborne, New Zealand",
  "Canterbury, New Zealand",
  "Nelson, New Zealand",
  "Waipara Valley, New Zealand",

  // Argentina
  "Mendoza, Argentina",
  "Salta, Argentina",
  "San Juan, Argentina",
  "Patagonia, Argentina",
  "La Rioja, Argentina",
  "Catamarca, Argentina",

  // Chile
  "Maipo Valley, Chile",
  "Colchagua Valley, Chile",
  "Casablanca Valley, Chile",
  "Aconcagua Valley, Chile",
  "Cachapoal Valley, Chile",
  "Leyda Valley, Chile",
  "San Antonio Valley, Chile",
  "Maule Valley, Chile",
  "Bío-Bío Valley, Chile",
  "Elqui Valley, Chile",
  "Limarí Valley, Chile",

  // South Africa
  "Stellenbosch, South Africa",
  "Franschhoek, South Africa",
  "Constantia, South Africa",
  "Hemel-en-Aarde, South Africa",
  "Swartland, South Africa",
  "Robertson, South Africa",
  "Elgin, South Africa",
  "Paarl, South Africa",

  // Other Regions
  "Bekaa Valley, Lebanon",
  "Galilee, Israel",
  "Tokaj, Hungary",
  "Santorini, Greece",
  "Nemea, Greece",
  "Naoussa, Greece",
  "Algarve, Portugal",
  "Moldova",
  "Georgia",
  "Croatia",
  "Slovenia",
  "Switzerland",
  "England",
  "Canada",
  "Uruguay",
  "Brazil",
  "Mexico",
  "India",
  "China",
  "Japan",
] as const;

export const grapeVarietals = [
  // Red Grapes
  "Cabernet Sauvignon",
  "Merlot",
  "Pinot Noir",
  "Syrah/Shiraz",
  "Malbec",
  "Tempranillo",
  "Sangiovese",
  "Nebbiolo",
  "Grenache/Garnacha",
  "Zinfandel",
  "Cabernet Franc",
  "Petit Verdot",
  "Carménère",
  "Mourvèdre/Monastrell",
  "Barbera",
  "Dolcetto",
  "Gamay",
  "Petite Sirah",
  "Tannat",
  "Touriga Nacional",
  "Aglianico",
  "Nero d'Avola",
  "Primitivo",
  "Montepulciano",
  "Corvina",
  "Xinomavro",
  "Pinotage",
  "Cinsault",
  "Carignan",
  "Graciano",
  "Mencía",
  "Bobal",
  "Blaufränkisch",
  "Zweigelt",
  "St. Laurent",
  "Dornfelder",
  "Portugieser",
  "Pinot Meunier",
  "Trousseau",
  "Poulsard",
  "Lagrein",
  "Teroldego",
  "Schiava",
  "Kadarka",
  "Furmint",
  "Saperavi",
  "Plavac Mali",
  "Vranac",
  "Prokupac",

  // White Grapes
  "Chardonnay",
  "Sauvignon Blanc",
  "Riesling",
  "Pinot Grigio/Pinot Gris",
  "Chenin Blanc",
  "Gewürztraminer",
  "Viognier",
  "Albariño",
  "Grüner Veltliner",
  "Sémillon",
  "Muscadet/Melon de Bourgogne",
  "Verdicchio",
  "Fiano",
  "Vermentino",
  "Verdejo",
  "Godello",
  "Txakoli/Hondarrabi Zuri",
  "Assyrtiko",
  "Moschofilero",
  "Malagousia",
  "Roditis",
  "Torrontés",
  "Marsanne",
  "Roussanne",
  "Grenache Blanc",
  "Picpoul",
  "Bourboulenc",
  "Clairette",
  "Ugni Blanc/Trebbiano",
  "Cortese",
  "Arneis",
  "Garganega",
  "Glera/Prosecco",
  "Friulano",
  "Ribolla Gialla",
  "Malvasia",
  "Moscato/Muscat",
  "Müller-Thurgau",
  "Silvaner",
  "Scheurebe",
  "Bacchus",
  "Kerner",
  "Welschriesling",
  "Aligoté",
  "Chasselas",
  "Jacquère",
  "Altesse",
  "Petit Manseng",
  "Gros Manseng",
  "Colombard",
  "Folle Blanche",
  "Muscadelle",
  "Loureiro",
  "Arinto",
  "Fernão Pires",
  "Encruzado",
  "Alvarinho",
  "Trajadura",
  "Palomino",
  "Pedro Ximénez",
  "Macabeo/Viura",
  "Parellada",
  "Xarel-lo",
] as const;

export const wineStyles = [
  // Red Wine Styles
  "Light-bodied Red",
  "Medium-bodied Red",
  "Full-bodied Red",
  "Bold & Tannic Red",
  "Smooth & Fruity Red",
  "Earthy & Savory Red",
  "Spicy Red",

  // White Wine Styles
  "Crisp & Light White",
  "Aromatic White",
  "Rich & Full-bodied White",
  "Sweet White",
  "Bone Dry White",
  "Mineral & Zippy White",
  "Tropical & Fruity White",

  // Rosé Styles
  "Dry Rosé",
  "Off-dry Rosé",
  "Fruity Rosé",
  "Savory Rosé",

  // Sparkling Styles
  "Traditional Method Sparkling",
  "Tank Method Sparkling",
  "Pét-Nat",
  "Champagne",
  "Cava",
  "Prosecco",
  "Crémant",
  "Franciacorta",
  "Sekt",

  // Fortified & Dessert
  "Dry Sherry",
  "Sweet Sherry",
  "Port",
  "Madeira",
  "Marsala",
  "Vin Santo",
  "Ice Wine",
  "Late Harvest",
  "Noble Rot/Botrytis",
  "Fortified Muscats",

  // Other Styles
  "Orange/Skin Contact Wine",
  "Natural Wine",
  "Biodynamic Wine",
  "Organic Wine",
  "Low Intervention Wine",
  "Amphora-aged Wine",
  "Carbonic Maceration",
] as const;

export const flavorProfiles = [
  // Fruit Flavors
  "Black Cherry",
  "Blackberry",
  "Blackcurrant",
  "Blueberry",
  "Boysenberry",
  "Cranberry",
  "Fig",
  "Plum",
  "Prune",
  "Raspberry",
  "Red Cherry",
  "Red Currant",
  "Strawberry",
  "Apple",
  "Apricot",
  "Citrus",
  "Grapefruit",
  "Green Apple",
  "Lemon",
  "Lime",
  "Lychee",
  "Mango",
  "Melon",
  "Orange",
  "Passion Fruit",
  "Peach",
  "Pear",
  "Pineapple",
  "Quince",
  "Stone Fruit",
  "Tropical Fruit",
  "White Peach",

  // Floral & Herbal
  "Elderflower",
  "Honeysuckle",
  "Jasmine",
  "Lavender",
  "Orange Blossom",
  "Rose",
  "Violet",
  "Basil",
  "Bay Leaf",
  "Eucalyptus",
  "Grass",
  "Green Bell Pepper",
  "Herbs",
  "Jalapeño",
  "Mint",
  "Oregano",
  "Rosemary",
  "Sage",
  "Tea",
  "Thyme",
  "Tobacco",

  // Spice & Other
  "Anise",
  "Black Pepper",
  "Cinnamon",
  "Clove",
  "Ginger",
  "Nutmeg",
  "Vanilla",
  "White Pepper",
  "Almond",
  "Butter",
  "Caramel",
  "Cedar",
  "Chocolate",
  "Cocoa",
  "Coffee",
  "Cream",
  "Graphite",
  "Hazelnut",
  "Honey",
  "Leather",
  "Licorice",
  "Mineral",
  "Mushroom",
  "Oak",
  "Petrol",
  "Slate",
  "Smoke",
  "Toast",
  "Truffle",
  "Wet Stone",
] as const;

export type WineRegion = (typeof wineRegions)[number];
export type GrapeVarietal = (typeof grapeVarietals)[number];
export type WineStyle = (typeof wineStyles)[number];
export type FlavorProfile = (typeof flavorProfiles)[number];
