name: Vinho
options:
  bundleIdPrefix: com.strategicnerds
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  createIntermediateGroups: true
  usesTabs: false
  indentWidth: 2
  tabWidth: 2
settings:
  base:
    DEVELOPMENT_TEAM: "955GSY56UT"
    CODE_SIGN_IDENTITY: "Apple Development"
    CODE_SIGNING_REQUIRED: YES
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    ENABLE_PREVIEWS: YES
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UIStatusBarStyle: UIStatusBarStyleLightContent
    INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
    INFOPLIST_KEY_UISupportedInterfaceOrientations~ipad: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown"
    INFOPLIST_KEY_NSCameraUsageDescription: "Vinho needs camera access to scan wine labels"
    INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "Vinho needs photo library access to upload wine images"
    INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "Vinho uses your location to show nearby wine regions"
targets:
  Vinho:
    type: application
    platform: iOS
    sources:
      - Vinho
    dependencies:
      - package: Supabase
      - package: Kingfisher
      - package: Lottie
      - package: PostHog
    preBuildScripts:
      - name: Fetch Doppler Secrets
        script: |
          if [ -f "$SRCROOT/Scripts/fetch-doppler-secrets.sh" ]; then
            bash "$SRCROOT/Scripts/fetch-doppler-secrets.sh"
          fi
        showEnvVars: false
        basedOnDependencyAnalysis: false
        outputFiles:
          - $(SRCROOT)/Vinho/DopplerSecrets.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.strategicnerds.vinho
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR: AccentColor
        CURRENT_PROJECT_VERSION: "1"
        MARKETING_VERSION: "1.0.0"
        CODE_SIGN_ENTITLEMENTS: Vinho/Vinho.entitlements
schemes:
  Vinho:
    build:
      targets:
        Vinho: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift
    from: 2.0.0
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher
    from: 7.10.0
  Lottie:
    url: https://github.com/airbnb/lottie-ios
    from: 4.4.0
  PostHog:
    url: https://github.com/PostHog/posthog-ios
    from: 3.8.3