import Foundation

/// Manages secrets from Doppler
/// The Config.plist is generated at build time by the Doppler script
class SecretsManager {
    static let shared = SecretsManager()

    private var secrets: [String: Any] = [:]

    private init() {
        loadSecrets()
    }

    private func loadSecrets() {
        // Try to load from Config.plist (generated at build time)
        if let url = Bundle.main.url(forResource: "Config", withExtension: "plist"),
           let data = try? Data(contentsOf: url),
           let plist = try? PropertyListSerialization.propertyList(from: data, format: nil) as? [String: Any] {
            self.secrets = plist
            #if DEBUG
            debugLog("Loaded \(secrets.count) secrets from Doppler")
            #endif
        } else {
            #if DEBUG
            debugLog("Config.plist not found in bundle. Secrets will be unavailable.")
            debugLog("Run the Doppler build script to generate Config.plist")
            #endif
            // Security: Do not load secrets from environment variables
            // All secrets must come from the secure Config.plist generated by Doppler
            self.secrets = [:]
        }
    }

    #if DEBUG
    private func debugLog(_ message: String) {
        // Only log in debug builds
    }
    #endif

    // Security: Removed loadFallbackSecrets() that read from environment variables
    // All secrets must be provided via the secure Config.plist generated by Doppler at build time
    // This prevents accidental exposure of secrets through environment variables

    /// Get a string secret
    func string(for key: String) -> String? {
        return secrets[key] as? String
    }

    /// Get a required string secret (crashes if not found)
    func requiredString(for key: String) -> String {
        guard let value = string(for: key), !value.isEmpty else {
            fatalError("Required secret '\(key)' not found in Doppler secrets")
        }
        return value
    }

    /// Get an integer secret
    func integer(for key: String) -> Int? {
        if let stringValue = secrets[key] as? String {
            return Int(stringValue)
        }
        return secrets[key] as? Int
    }

    /// Get a boolean secret
    func boolean(for key: String) -> Bool? {
        if let stringValue = secrets[key] as? String {
            return stringValue.lowercased() == "true" || stringValue == "1"
        }
        return secrets[key] as? Bool
    }

    /// Get a URL from a secret
    func url(for key: String) -> URL? {
        guard let urlString = string(for: key) else { return nil }
        return URL(string: urlString)
    }
}